### ISSUE TITLE
Support :case_insensitive diff-ing option

### ISSUE THREAD

**Issue by ronco** [liufengyun/hashdiff#13]
Similar to `:strip` and `:numeric_tolerance` I think it would be useful to have an option to make string comparisons case insensitive.  I'm happy to provide a PR if there would be interest in adding this feature.

**Comment by scalp42** [comment]
@ronco would be great!

**Comment by ronco** [comment]
Will do. I'll try to put it together this weekend.

**Comment by liufengyun** [comment]
It's definitely welcomed, thx @ronco .

**Comment by ronco** [comment]
Just submitted PR #14 for this.  Let me know what you think.
