### ISSUE TITLE
Custom similar? method

### ISSUE THREAD

**Issue by jembezmamy** [liufengyun/hashdiff#15]
I'm not sure if I understand properly your code, but I feel it would be great to allow to define custom `similar?` method.

And that's my use case: I have an array of serialized Rails models. In this case `similar?` should use object's ids rather than comparing their content.

```ruby
before = [{id: 1, name: "Peter"}, {id: 2, name: "John"}]
after = [{id: 2, name: "Peter"}, {id: 3, name: "Ann"}]

# current behavior
HashDiff.diff(before, after, similarity: 0.5)
# [
#   ["~", "[0].id", 1, 2], ["-", "[1]", {:id=>2, :name=>"John"}],
#   ["+", "[1]", {:id=>3, :name=>"Ann"}]
# ] 

# my proposition
HashDiff.diff(before, after, similar: -> (a, b, options) { a[:id] === b[:id] })
# [
#   ["~", "[1].name", "John", "Peter"],
#   ["-", "[0]", {:id=>1, :name=>"Peter"}],
#   ["+", "[1]", {:id=>3, :name=>"Ann"}]
# ] 
```

Of course I can get the same results by modifying `HashDiff.similar?` method (which I did), but it would be nice if I could do the same thing locally – just like custom comparison method.

It's just an idea, maybe a bad one, since I don't really understand this whole similarity mechanism. :smile: Thank you for this gem, it's elegant and very useful!

**Comment by liufengyun** [comment]
@jembezmamy thanks for reporting the issues.

Currently the lib supports following feature, which seems to be able to do what you want:

``` Ruby
diff = HashDiff.diff(a, b) do |path, obj1, obj2|
  case path
  when '[*]'
    obj1.id == obj2.id
  end
end
```

**Comment by liufengyun** [comment]
Closing this for now, please reopen if the above doesn't satisfy what you need.
