### ISSUE TITLE
ArgumentError with heterogenous keys

### ISSUE THREAD

**Issue by wimrijnders** [liufengyun/hashdiff#16]
I encountered an ArgumentError while comparing hashes which has keys of mixed string and symbols. While this practice is without doubt questionable, I do expect HashDiff to be able to handle this gracefully.

The following small example shows this:

```ruby
require 'hashdiff'
a = { "c" => "testing", :b => "one two" }
b = { :a => "testing", "b" => "three four" }
HashDiff.diff a, b
```
Results in:
```text
ArgumentError: comparison of String with :b failed
        from /home/user/.rvm/gems/ruby-2.1.5/gems/hashdiff-0.3.0/lib/hashdiff/diff.rb:130:in `sort'
        from /home/user/.rvm/gems/ruby-2.1.5/gems/hashdiff-0.3.0/lib/hashdiff/diff.rb:130:in `diff'
        from (irb):14
        from /home/user/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

This occurs in method `self.diff` in file diff.rb, and can happen at the places where key arrays are sorted, e.g.:
```ruby
deleted_keys.sort.each do |k|
...
added_keys.sort.each do |k|
```

The best solution I can think of, is to replace the default sort with something that can handle any type, as long as that type implements to_s:

```ruby
deleted_keys.sort {|x,y| x.to_s <=> y.to_s}.each do |k|
...
end
```

This works but is ugly, it could use some refactoring. The weak part of this solution is that it depends on the presence of method to_s to work. But this at least is a step toward a more generic usage.

**Comment by liufengyun** [comment]
@wimrijnders thanks for reporting this issue.

Actually I'm considering removing `sort`, it's only required for deterministic test in `1.8.7`. Assuming keys serialisable is actually acceptable, as it's a basic assumption of this library.

BTW, if you expect the library to treat `"b"` and `:b` as the same, probably you can consider using `indifferent_access`.

**Comment by wimrijnders** [comment]
Thanks for answering.

Removing sort sounds like a good idea to me.

"b" and :b are regarded as different in my application, although I have to admit it's a legacy kludge. I'd be happy to get rid of it.

**Comment by liufengyun** [comment]
There's another inherent problem with the presence of both string keys and symbolic keys:

```
a = { :x => 5 }
b = { 'x' => 5 }

diff(a, b) = [['-', 'x', 5], ['+', 'x', '5']]
```

This diff would be very confusing to users. I've no idea how to handle this elegantly. Maybe just like in JavaScript, we assume all keys to be string.

**Comment by wimrijnders** [comment]
Well the following would work (line 136 diff.rb):

```ruby
result << ['-', k, obj1[k]]
```

...but I have no idea how to handle the prefix variable in the original:
```ruby
result << ['-', "#{prefix}#{k}", obj1[k]]
```

What's it for?

**Comment by liufengyun** [comment]
@wimrijnders To support any type of keys, it suffices to treat the second component as an array of keys, instead of strings.

I'm not sure how useful that approach is. However, it does complicate the interface. My original usage scenario is for diff JSON, I want to keep the API simple for that usage.

There are two options now:

- support a different mode of comparison allowing all types of keys
- create a new gem to support all types of keys

As this is an open source project, all kinds of contributions would be appreciated.

**Comment by wimrijnders** [comment]
>  My original usage scenario is for diff JSON, I want to keep the API simple for that usage.

In that case, don't allow any other keys. As a minimum, I would suggest:

- Explicitly block any non-string keys; generate an error if they're present.
- Also, explicitly mention that it's for JSON diff's and it applies to string keys only.

I see no reason to move outside the spec's, if the spec's are specifically for JSON. Especially if it's obvious that handling other key types entails way too much work.

And I'll just fix the silly symbol keys in my application. Sorry to have bothered you with this.

**Comment by liufengyun** [comment]
Thanks for your suggestion. And if you ever encounter a scenario that necessitates all types of keys, forking the repo and making tweaks is actually affordable -- only need to replace string concatenation with array concatenation.

**Comment by wimrijnders** [comment]
Just updated today due to full reinstall of my laptop.

Happy to say that the thing discussed in this issue now works!
Unit tests failing, but in a good way.
