### ISSUE TITLE
sort array inside hash automatically

### ISSUE THREAD

**Issue by rajatjindal83** [liufengyun/hashdiff#22]
I find this library to be extremely useful, however its missing a usecase that i badly need.

As you mentioned in the documentation, if we have array inside hash, it will need to be sorted before we can compare, else it will show them as diff.

Can we please add a option to sort arrays before comparing them? is there any specific reason why its not provided?

Thanks
Rajat JIndal

**Comment by liufengyun** [comment]
@rajatjindal83 it seems difficult to arrive at a reasonable way to sort arrays with arbitrary objects.
