### ISSUE TITLE
Patch problem whit symbol as key

### ISSUE THREAD

**Issue by gmgp** [liufengyun/hashdiff#25]
From Readme

```
require 'hashdiff'          #=> true
a = {a: 3}                  #=> {:a=>3}
b = {a: {a1: 1, a2: 2}}     #=> {:a=>{:a1=>1, :a2=>2}}
diff = HashDiff.diff(a, b)  #=> [["~", "a", 3, {:a1=>1, :a2=>2}]]

HashDiff.patch!(a, diff)   #=> {:a=>3, "a"=>{:a1=>1, :a2=>2}}
```

rspec files check only string keys

**Comment by liufengyun** [comment]
Sorry for the late reply, @gmgp . Yes, there's problem with patch for symbol, because the assumption of the lib to represent keys as paths, which are basically strings. I see no easy way to work around this limitation, given our current assumption.

**Comment by zacksiri** [comment]
I can verify that adding `array_path: true` works, the issue can be closed. @liufengyun

**Comment by liufengyun** [comment]
Thanks @zacksiri !
