### ISSUE TITLE
Ruby 1.8.7 compatibility

### ISSUE THREAD

**Issue by donaldali** [liufengyun/hashdiff#38]
The gemspec file indicates compatibility from ruby 1.8.7 while travis.yml sets up testing from ruby 1.9.3. If compatibility is supposed to be from ruby 1.8.7, then [this line](https://github.com/liufengyun/hashdiff/blob/master/lib/hashdiff/linear_compare_array.rb#L46) breaks that compatibility by using the ruby 1.9 hash syntax.

**Comment by liufengyun** [comment]
Yes, `1.8.7` is not supported also for some other issue about some ordering change in testing. I forgot to update the gemspec file.

**Comment by krzysiek1507** [comment]
Minimum Ruby 2.0 is required.
