### ISSUE TITLE
Can’t silence HashDiff constant warning

### ISSUE THREAD

**Issue by tomstuart** [liufengyun/hashdiff#68]
Thanks to the warning from #65, I am now aware of the `HashDiff`/`Hashdiff` conflict. I have updated my code to use the correct `Hashdiff` constant.

Now that I’ve done the work to fix the issue, how do I turn the warning off?

**Comment by jfelchner** [comment]
@tomstuart we'll be releasing `1.0` shortly.

**Comment by nacengineer** [comment]
@tomstuart one way is to put 

$VERBOSE = nil

at the top of your gemfile. Just be aware this will silence all deprecation warnings.

**Comment by jfelchner** [comment]
@tomstuart I just realized we can release a beta for `1.0` which will allow people annoyed by the warnings to manually opt-in to the breaking change until we're ready to release `1.0` final. :)

See my comment on the original issue as well as [this PR](https://github.com/liufengyun/hashdiff/pull/70)

**Comment by tomstuart** [comment]
@jfelchner That would be perfect. Thank you!

**Comment by jfelchner** [comment]
@tomstuart Awesome :) Can you close this issue please?

**Comment by gshutler** [comment]
In case anyone else ends up here and has to look up how to loosely define a beta version and upwards as you don't do it too often, this is about the same as `~> 1.0`:

```ruby
gem 'hashdiff', '>= 1.0.0.beta1', '< 2.0.0'
```
