### ISSUE TITLE
Showing same count as `=`

### ISSUE THREAD

**Issue by zenati** [liufengyun/hashdiff#7]
Hello,

Actually Hashdiff can show `+`, `-` and `~`.
Is it possible to also show same counts in the diff as `=` ?

example output:

```
['-', 'b', 2], ['+', 'a', 4], ['=', 'c', 3, 3], ['~', 'd', 3, 8] 
```

Thanks.

**Comment by AAverin** [comment]
Was that feature implemented in the end?
Would be very nice to have it

**Comment by pchaganti** [comment]
:+1:

**Comment by liufengyun** [comment]
Thanks for your interest in this lib. I'm wondering what would you like to be the output in following case:

``` ruby
diff({a: {x: 2} }, {a: {x: 2} })
```

Possible result A:

```ruby
[['=', 'a', {x: 2}]]
```

Possible result B:

```ruby
[['=', 'a.x', 2]]
```

To me, the result A is more natural, but it means the algorithm needs to traverse the object twice -- first check if they are exactly equal(without `=`); if not, parse again to get all the `=` cases.
